### PR TITLE
Improve lhs_optimal.c

### PR DESCRIPTION
**Pull request by jbect**
Please pull this branch which provides various improvements to LHS_Optimal.c

### CODE REVIEW

**Comment by jbect** [comment]
Wait !  I have made a mistake...

**Comment by jbect** [comment]
I said wait...

**Comment by gaoyuantim** [comment]
I'm sorry, Do you need to revert the changes?

**Comment by jbect** [comment]
No, wait

**Comment by jbect** [comment]
I didn't know how to continue this PR, so I created another to fix the problem introduced by this one.

**Pull request merged**
